package_name: "robot_mindset_linux"
environment: "debian"
version: "1.0"

docker:
    registry: "container-registry.gitlab.cc-asp.fraunhofer.de/multirobot"

dockerfile:
    base:
        from: "debian:12"
        tag: "robot_mindset_linux:base-1.0"
        cmd: ["bash"]
        build: True
        build_arguments:
            secret: id=gitcreds,src=$HOME/.git-credentials
        registry:
            tag: "robotmindset/robot_mindset_linux:base-1.0"
        order: 0
    devcontainer:
        from: "robot_mindset_linux:base-1.0"
        tag: "robot_mindset_linux:devcontainer-1.0"
        cmd: ["bash"]
        build: False
        order: 1
    ci:
        from: "robot_mindset_linux:base-1.0"
        tag: "robot_mindset_linux:ci-1.0"
        cmd: ["bash"]
        build: True
        build_arguments:
            secret: id=gitcreds,src=$HOME/.git-credentials
        registry:
            tag: "robotmindset/robot_mindset_linux:ci-1.0"
        build_cmd: ""
        order: 1
    run:
        from: "robot_mindset_linux:base-1.0"
        tag: "robot_mindset_linux:run-1.0"
        cmd: ["bash", "-c", "echo hi"]
        registry:
            tag: "robotmindset/robot_mindset_linux:run-1.0"
        build: True
        build_keep_folders: ['/root/.conan2', '/opt/dev-setup', '/opt/robot_mindset']
        build_arguments:
            secret: id=gitcreds,src=$HOME/.git-credentials
        order: 2

entrypoint:
    source: []

devcontainer:
    vscode:
        extensions: ["ms-python.python",
                    "ms-vscode.cpptools-extension-pack",
                    "ms-vscode.cmake-tools",
                    "redhat.vscode-xml",
                    "mhutchie.git-graph",
                    "ms-azuretools.vscode-docker",
                    "mtsmfm.vscode-stl-viewer",
                    "cschlosser.doxdocgen",
                    "samuelcolvin.jinjahtml"]
    feature:
        packages: "ssh,curl,nano,python3-pip,git"
        desktop_lite: "False"