environments:
  - environment: dev
    image: ubuntu-24.04.2-desktop-amd64.iso
    autoinstall: 
      source:
        id: ubuntu-desktop-minimal
    data:
      debs: data/dev/debs
      ansible: data/dev/ansible

  - environment: run
    image: ubuntu-22.04.5-live-server-amd64.iso
    autoinstall: 
      source:
        id: ubuntu-server-minimal
    data:
      debs: data/run/debs
