environment: dev

networks:
  - name: public
    match:
      macaddress: BC:24:11:4F:59:90
  - name: machine
    ipv4: 192.168.1.10/24
    match:
      macaddress: BC:24:11:DF:88:30

autoinstall:
  identitiy:
    hostname: robot_mindest
    realname: Setup
    username: setup
    password: $6$F.awLTnjnE0ZY0tW$WzojF4xYqYYAHgf0uEDJI4MfCd98VqL3EL/oVWXLrTsykOWkpO7YAV69BR4M6JZtkeT5v4KILd0SJRxpINLm50 # setup -> crypt.METHOD_SHA512
  storage:
    password: setup
    boot:
      size: 9G
    disk:
      match: size.largest # size.largest, ssd

  # packages:
  #   - curl
  #   - docker-buildx
  #   ## --- dev --- 
  #   # - ubuntu-desktop
  #   - ansible
  #   - git
  #   - python3
  #   - python3-pip
  #   - python3-venv
  #   - cloud-image-utils
  #   - inkscape

  ssh:
    authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIS0ToieXEJK+fzlwqKIc7LGg24vSLqb6y1Nfqne0lCH mdh@ipa.robot-mindset.1password

  late_commands:
    - curtin in-target --target /target bash /robot_mindset/data/install.sh || true
